// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function InitialPath() {
  return window['go']['main']['App']['InitialPath']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function PendingPaths() {
  return window['go']['main']['App']['PendingPaths']();
}

export function PrintWindow() {
  return window['go']['main']['App']['PrintWindow']();
}

export function SavePNG(arg1, arg2) {
  return window['go']['main']['App']['SavePNG'](arg1, arg2);
}

export function WebSocketConfig() {
  return window['go']['main']['App']['WebSocketConfig']();
}
