// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfo():Promise<main.appInfo>;

export function InitialPath():Promise<string>;

export function OpenFile():Promise<string>;

export function PendingPaths():Promise<Array<string>>;

export function PrintWindow():Promise<void>;

export function SavePNG(arg1:string,arg2:string):Promise<string>;

export function WebSocketConfig():Promise<main.webSocketConfig>;
